import "~/styles/globals.css";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      
    <html lang="en" className={`${GeistSans.variable}`}>
    <body className={`dark bg-gray-900 text-white ${inter.className}`}>
        <main className="p-4">
        <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
          {children}
        </main>
      </body>
    </html>
    </ClerkProvider>
  );
}
